### PR TITLE
Adds TavernAI Output (Tested Chrome & FF)

### PR DESCRIPTION
**Pull request by BowNArrowPro20**
Adds TavernAI output, well supposed to. I have to look into testing it but I'll push it so you can have it too.

Pretty sure I covered my bases but say otherwise.

### CODE REVIEW

**Comment by BowNArrowPro20** [comment]
Ok I have found out how to test so I will do that now. Wish me luck.

**Comment by BowNArrowPro20** [comment]
Seems to be working on chrome, testing ff now...

**Comment by BowNArrowPro20** [comment]
Tested, does load to tavernAI fine :)

Now firefox test.

**Comment by BowNArrowPro20** [comment]
Seems to work, assuming that all you do for ff version is copy files into the ffversion folder, since with that I was able to get it working properly locally.

So..Should work fully now! Yay!

**Comment by memmam** [comment]
Hey in the meantime can you send a packaged .zip of this extension so I can install it?

**Comment by BowNArrowPro20** [comment]
> Hey in the meantime can you send a packaged .zip of this extension so I can install it? I have a need for this exact functionality.

You can download 'my version' directly off of git at [my branch here.](https://github.com/BowNArrowPro20/CAI-Tools)

Then you can load the extension via [this for chrome](https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#load-unpacked) or [here for firefox.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing)

For firefox once you dl the zip you just have to take all the files from the main folder and move them to the folder called 'FirefoxVersion', and when the popup asks about overwriting duplicates just press skip.

Make sure you disable the normal extension when you load it locally, otherwise they'll probably conflict.

If you have any questions or need any more help feel free to ask!

**Comment by BowNArrowPro20** [comment]
Oh yeah I should update readme as well hm..?

**Comment by memmam** [comment]
I figured it out, it says the extension is corrupt if I try to install it instead of loading it through debug since it's self-signed.

**Comment by BowNArrowPro20** [comment]
> I figured it out, it says the extension is corrupt if I try to install it instead of loading it through debug since it's self-signed.

Yeah I can't do much about that since it isn't my extension. Why I did the pull so it can just be part of the extension proper, but loading it via debug works for now yes? You did get it working?

**Comment by memmam** [comment]
Yeah it's working. I'm trying to build a massive character dialogue dataset for future AI experimentation, using a combination of c.ai and GPT-4 x Alpaca 30B int4, and I was previously having to do manual JSON surgery on entire cai-dumps to import c.ai conversations into SillyTavern, so this actually is a huge help.

**Review by irsat000 — APPROVED** [review]
Looks good! Thank you for your contribution.

**Pull request merged**
